
llm_agents:
  writer_1:
    model: openai/gpt-4o-mini
    template: |
      Could you write me a haiku?
      
  writer_2:
    model: openai/gpt-4o-mini
    template: |
      Could you write me a poem?

  eval_agent:
    model: openai/gpt-4o-mini
    template: rating_5_star
    template_params:
      criteria: |
        1. Make sure sentences are concise and don't use flowery language.
        2. It shouldn't sound too salesy or promotional.
        3. Don't use too many adjectives or adverbs.
        4. Don't make general claims.
        5. Don't start with a question.
    json_mode: on

