
llm_agents:
  summary_writer:
    model: openai/gpt-4o-mini
    template: |
      Provide a summary of the latest {{ product_type }} sales performance 
      in the {{ region }} market for {{ time_period }}. 
      
      Include key metrics such as {{ metric_1 }} and {{ metric_2 }}. 
      Also, highlight any significant trends or factors affecting sales 
      in this region.

  eval_agent:
    model: openai/gpt-4o-mini
    template: rating_5_star
    template_params:
      criteria: |
        1. Make sure sentences are concise and don't use flowery language.
        2. It shouldn't sound too salesy or promotional.
        3. Don't use too many adjectives or adverbs.
        4. Don't make general claims.
        5. Don't start with a question.
    json_mode: on

